app = "kalaclista-social-v2"
primary_region = "nrt"

kill_signal = "SIGTERM"
kill_timeout = 10

swap_size_mb = 512

[deploy]
strategy = "rolling"

[[services]]
  internal_port = 9080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 50
    soft_limit = 25
    type = "connections"

  [[services.port]]
  handlers = ["http"]
  port = 80
  force_https = true

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443

  [[services.tcp_checks]]
  grace_period = "5s"
  interval = "10s"
  restart_limit = 0
  timeout = "10s"

[[mounts]]
destination = "/data"
source = "kalaclista_social_data"
