# fly.toml app configuration file generated for kalaclista-social-v3 on 2024-11-02T17:38:23+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kalaclista-social-v3'
primary_region = 'iad'
kill_signal = 'SIGTERM'
kill_timeout = '30s'
swap_size_mb = 1024

[deploy]
  strategy = 'rolling'

[[mounts]]
  source = 'kalaclista_social_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false

  [[http_service.checks]]
    method = 'GET'
    path = '/.well-known/healthcheck'
    protocol = 'http'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
