app = "kalaclista-social-v2"
primary_region = "nrt"

kill_signal = "SIGTERM"
kill_timeout = 30

swap_size_mb = 512

[deploy]
strategy = "rolling"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  [[http_service.checks]]
    protocol = "http"
    method = "GET"
    path = "/.well-known/healthcheck"

[[mounts]]
destination = "/data"
source = "kalaclista_social_data"
